<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="Styles\input.css" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="About\Models\" />
    <Folder Include="Contact\Models\" />
    <Folder Include="Home\Models\" />
    <Folder Include="Data\" />
    <Folder Include="Projects\Models\" />
  </ItemGroup>

</Project>
